name: ramflux_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_slidable: ^3.0.1
  flutter_svg: ^2.0.9
  flutter_easyloading: ^3.0.5
  get: ^4.6.6
  google_fonts: ^6.1.0
  intl: ^0.18.1
  pinput: ^3.0.1
  pull_to_refresh_flutter3: ^2.0.2
  shared_preferences: ^2.2.2
  animations: ^2.0.11
  badges: ^3.1.2
  bip39: ^1.0.6
  carousel_slider: ^4.2.1
  extended_image: ^8.2.0
  flex_color_scheme: ^7.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.9

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/google_fonts/Poppins/
